CREATE TABLE usuarios (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login VARCHAR2(100) NOT NULL UNIQUE,
    senha VARCHAR2(255) NOT NULL,
    perfil VARCHAR2(50) DEFAULT 'COMUM' NOT NULL,
    ativo NUMBER(1) DEFAULT 1 NOT NULL
);

INSERT INTO usuarios (login, senha, perfil, ativo)
VALUES ('admin@autoescola.com', '$2a$10$1MOtkCKhl6v/GzivJpSk4uKQ0knOct1tHZfuHu8gd36WW5UHAAZoq', 'ADMIN', 1);
