CREATE TABLE instrucoes (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aluno_id NUMBER(19) NOT NULL,
    instrutor_id NUMBER(19) NOT NULL,
    data TIMESTAMP NOT NULL,
    motivo_cancelamento VARCHAR2(50),
    CONSTRAINT fk_instrucoes_aluno FOREIGN KEY (aluno_id) REFERENCES alunos(id),
    CONSTRAINT fk_instrucoes_instrutor FOREIGN KEY (instrutor_id) REFERENCES instrutores(id)
);
